Add 01-RISC-V-spoc-zh.md
plctlab/rvspoc pull request #20
Opened 2023-11-27 13:11 UTC by sunmin89

2023-11-27 13:15 UTC, shiptux commented on content/zh/posts/01-RISC-V-spoc-zh.md
> +title = '拥抱开源生态，算能携手软件所 PLCT 实验室联合举办 RISC-V 软件移植优化锦标赛'
Should not use zh in the file name.

2023-11-28 06:31 UTC, shiptux commented on content/zh/posts/01-RISC-V-spoc-zh.md
> +title = '拥抱开源生态，算能携手软件所 PLCT 实验室联合举办 RISC-V 软件移植优化锦标赛'
The versions in different languages need to keep the same file names.

2023-11-28 06:46 UTC, shiptux requested changes

2023-11-28 06:46 UTC, shiptux commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +- SG2042 / Pioneer Box
Should remove the spaces between SG2042 and Pioneer Box.

2023-11-28 06:46 UTC, shiptux commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +- CV1800B / Milk-V Duo
Ditto.

2023-11-28 06:46 UTC, shiptux commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +RISC-V 已在 MCU/IoT 领域出货数十亿，正向桌面计算、HPC、AI、数据中心等大算力领域挑战。今天，几乎所有流行的 Linux 操作系统发行版已积极支持 RISC-V 架构，GNU Toolchain、Clang/LLVM、OpenJDK、V8、Spidermonkey 等工具链和运行时已在 RISC-V 平台上稳定运行。为了推动 RISC-V 生态迅速发展，算能作为 RISC-V
> 与 RISC-V  中国社区

Too many spaces between RISC-V and Chinese.

2023-11-28 06:46 UTC, shiptux commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +<table><tr><td bgcolor=#f4eeff>&ensp;&ensp;算能致力于成为全球领先的通用算力提供商，专注于深度学习、RISC-V 处理器等算力产品的研发和推广应用，遵循全面开源开放的生态理念 ，为互联网、城市运营、智算中心、泛安防、智能制造、AIGC 等应用场景提供算力产品及整体解决方案 。公司在北京、上海、深圳、青岛、厦门等国内 10 多个城市及美国、新加坡等国家设有
> 遵循全面开源开放的生态理念 ，

Should remove the space before the comma.

2023-11-28 06:46 UTC, shiptux commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +<table><tr><td bgcolor=#f4eeff>&ensp;&ensp;算能致力于成为全球领先的通用算力提供商，专注于深度学习、RISC-V 处理器等算力产品的研发和推广应用，遵循全面开源开放的生态理念 ，为互联网、城市运营、智算中心、泛安防、智能制造、AIGC 等应用场景提供算力产品及整体解决方案 。公司在北京、上海、深圳、青岛、厦门等国内 10 多个城市及美国、新加坡等国家设有
> 为互联网、城市运营、智算中心、泛安防、智能制造、AIGC 等应用场景提供算力产品及整体解决方案 。

Ditto.

2023-11-28 10:09 UTC, bekcpear requested changes

2023-11-28 10:09 UTC, bekcpear commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +summary = '为推动 RISC-V 软件生态加速发展，<font color=#916dd6> **算能作为 RISC-V 生态的领先企业，与 RISC-V 中国社区、中科院软件所 PLCT 实验室联合发起“RISC-V 软件移植及优化锦标赛”活动</font>**，以桌面和服务器软件生态为重点，在编译器、运行时环境、AI 软件栈等多个方面公开提出一系列比赛题目，邀请全球开发者完成挑战并
summary 里面不要有 HTML code

2023-11-28 10:09 UTC, bekcpear commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +
多余的空行可以删掉

2023-11-28 10:09 UTC, bekcpear commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +<center>官方指定验证平台：Duo</center>
这里的文字说明，建议改成

```
官方指定验证平台：Pioneer Box
<pioneer box 的图>

官方指定验证平台：Duo
<Duo 的图>
```

2023-11-28 10:09 UTC, bekcpear commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +![01_zh_pioneer_box](/images/posts/01_zh_pioneer_box_challenge.png)
表格不建议使用图片，直接改用 Markdown 的表格形式。

2023-11-28 10:09 UTC, bekcpear commented on content/zh/posts/01-RISC-V-spoc-zh-SOPHGO.md
> +“RV Software Porting & Opt Championship” Announced https://mp.weixin.qq.com/s/E20DM8PRXW67CFJ4vC739A
这里改用英文双引号

2023-11-28 12:41 UTC, bekcpear commented on content/zh/posts/01-RISC-V-spoc-SOPHGO.md
> +![01_zh_pioneer_duo](/images/posts/01_zh_pioneer_duo.png)
这个文件名多了 pioneer? 虽然实际不影响

2023-11-28 12:48 UTC, sunmin89 commented on content/zh/posts/01-RISC-V-spoc-SOPHGO.md
> +![01_zh_pioneer_duo](/images/posts/01_zh_pioneer_duo.png)
确实，我马上改一下

2023-11-29 01:23 UTC, bekcpear approved these changes

2023-11-29 01:51 UTC, merged