Add Korean translation
plctlab/rvspoc pull request #36
Opened 2023-12-02 14:04 UTC by alapha23

#17

2023-12-02 14:15 UTC, bekcpear requested changes

2023-12-04 10:46 UTC, alapha23 commented on content/ko/challenges/P2301.md
> +요약: '이 프로젝트에서는 OpenHarmony를 SG2042/Pioneer Box에 이식하고, 그래픽 인터페이스를 시작하여 기본적인 인터넷 브라우징, 오피스 작업 등을 수행할 수 있어야 합니다.'
改好了，谢谢

2023-12-04 10:52 UTC, bekcpear commented on content/ko/challenges/P2301.md
> +제목 = 'SG2042에서 OpenHarmony 이식 및 데모스트레이션'
所有文章头部两个
+++
+++

里面的内容，前面的 title date 之类的是健名 不能翻译

2023-12-04 10:59 UTC, bekcpear commented
以及日文这里有个小更新 可以一起改了 https://github.com/plctlab/rvspoc/blob/main/content/ja/challenges/_index.md

2023-12-04 11:09 UTC, bekcpear approved these changes
Thanks very much!

2023-12-04 11:10 UTC, merged