Add docs for S2305
plctlab/rvspoc pull request #78
Opened 2024-01-22 03:44 UTC by sunmin89

2024-01-22 09:40 UTC, shiptux requested changes

2024-01-22 10:38 UTC, bekcpear reviewed
一些 Markdown 的格式问题

2024-01-22 10:38 UTC, bekcpear commented on Docs/S2305/S2305.md
> +<br /><br /><br /><br /><br /><br /><br />
这个直接截图？+ 链接
不然赛题页面更新后，这里看起来得跟着更新。。

2024-01-22 10:38 UTC, bekcpear commented on Docs/S2305/S2305.md
> +```
列表级别下的代码块，通常会有与列表一样的锁进，比如此处应为：

<pre>
- openGauss-third_party 源码获取
  ```
  git clone git@github.com:opengauss-mirror/openGauss-third_party.git
  ```
</pre>

才不会破坏列表布局

**下同**

2024-01-22 10:38 UTC, bekcpear commented on Docs/S2305/S2305.md
> +- 尝试单个编译 third_party 中的依赖 （openssl）
markdown 不同的元素之间，需要空行，其他类似问题同

2024-01-22 10:38 UTC, bekcpear commented on Docs/S2305/S2305.md
> +
多余空行，可能会导致代码块内的额外空行。

2024-01-22 10:38 UTC, bekcpear commented on Docs/S2305/S2305.md
> +\l
这里是否需要包裹代码块？

2024-01-23 15:13 UTC, sunmin89 commented on Docs/S2305/S2305.md
> +- 尝试单个编译 third_party 中的依赖 （openssl）
有疑问：
因为备注这里，图片属于上一个列表元素，你是指两个列表元素之间需要空行，还是说列表元素的文本与列表元素的图片之间需要空行

比如下面这样：
![image](https://github.com/plctlab/rvspoc/assets/17847861/bd79eee9-b66f-45b5-b307-f80f6c95939a)

2024-01-23 15:28 UTC, bekcpear commented on Docs/S2305/S2305.md
> +- 尝试单个编译 third_party 中的依赖 （openssl）
如果你是需要表示列表的每个元素的正文的话，是需要对每个列表元素的内容进行缩进的，缩进符合当前列表首个内容的缩进尺寸，列表元素内的正文，通常来说，需要换行，但是不换行 GitHub 也能识别（但是列表每个元素之间，不能换行），比如，你这里可能需要的的修改到的内容是：

<pre>
### 开源软件编译 (openGauss-third_party)

- 仓库地址 https://github.com/opengauss-mirror
- openGauss-third_party 源码获取
  ```
  git clone git@github.com:opengauss-mirror/openGauss-third_party.git
  ```
- third_party 整体编译
  ```
  cd openGauss-third_party/build
  #查看系统自带 gcc 版本信息
  gcc -v
  bash build_all.sh
  ```

  ![build-all-third-party-vbox](build-all-third-party-vbox.png)
- 尝试单个编译 third_party 中的依赖 （openssl）
  ```
  cd /home/sunmin/smin/openGauss-third_party/dependency/openssl
  python3 build.py -m all -f openssl-1.1.1g.tar.gz -t "comm|llt"
  ```
- 手动下载 openssl-1.1.1g.tar.gz 之后重新编译
  ```
  wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz
  python3 build.py -m all -f openssl-1.1.1g.tar.gz -t "comm|llt"
  ```

  ![openssl-vbox-ok](openssl-vbox-ok.png)
- 尝试单个编译 third_party 中的依赖 （libxml2）
  ```
  cd /home/sunmin/openGauss-third_party/dependency/libxml2
  sh build.sh  -m all
  ```

  ![tar-format](tar-format.png)
- 下载正确的 tar 包之后，再次编译 libxml2
  ```
  rm libxml2-2.9.9.tar.gz
  wget ftp://xmlsoft.org/libxml2/libxml2-2.9.9.tar.gz
  sh build.sh  -m all
  ```

  ![build-xml2-vbox](build-xml2-vbox.png)
</pre>

2024-01-24 06:06 UTC, shiptux approved these changes

2024-01-24 07:35 UTC, merged